server:
  http2:
    enabled: true
  tomcat:
    connection-timeout: 4000
    threads:
      max: 300
      min-spare: 60
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-FORWARDED-FOR
      port-header: X-Forwarded-Port

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        batch_fetch_style: DYNAMIC
        order_inserts: true
        update_inserts: true
        jdbc:
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true
          time_zone: UTC
        generate_statistics: false

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

springdoc:
  swagger-ui:
    path: /documentation