spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/internationales-haus}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        batch_fetch_style: DYNAMIC
        order_inserts: true
        update_inserts: true
        jdbc:
          batch_size: 100
          fetch_size: 100
          batch_versioned_data: true
          time_zone: UTC
        generate_statistics: false

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

admin:
  username: ${ADMIN_USERNAME:adminUserName}
  password: ${ADMIN_PASSWORD:adminPassword}

jwt:
  secret: ${JWT_SECRET:WZD+yI3tlH3YKeq2pQ9y8IqaRAW/my8S55+HJKyqcu0=}
  expiration: ${JWT_EXPIRATION:86400000}
